from .algorithms.compression_algorithm_zip import ZipAlgorithm
from .algorithms.compression_algortihm_gzip import GzipAlgorithm
from .algorithms.compression_algorithm_zstd import ZstdAlgorithm
from .algorithms.compression_algorithm_brotli import BrotliAlgorithm

from .compression_algorithm import CompressionAlgorithm
from .compression_utils import CompressionUtils
